# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ClientDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Clientinit(object):
    def setupUi(self, Clientinit):
        Clientinit.setObjectName("Clientinit")
        Clientinit.resize(445, 198)
        self.label = QtWidgets.QLabel(Clientinit)
        self.label.setGeometry(QtCore.QRect(20, 40, 81, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Clientinit)
        self.label_2.setGeometry(QtCore.QRect(40, 80, 54, 12))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Clientinit)
        self.label_3.setGeometry(QtCore.QRect(20, 120, 71, 16))
        self.label_3.setObjectName("label_3")
        self.ClientIP = QtWidgets.QLineEdit(Clientinit)
        self.ClientIP.setGeometry(QtCore.QRect(100, 40, 221, 20))
        self.ClientIP.setObjectName("ClientIP")
        self.Clientport = QtWidgets.QLineEdit(Clientinit)
        self.Clientport.setGeometry(QtCore.QRect(100, 80, 111, 20))
        self.Clientport.setObjectName("Clientport")
        self.Cunit = QtWidgets.QLineEdit(Clientinit)
        self.Cunit.setGeometry(QtCore.QRect(100, 120, 111, 20))
        self.Cunit.setObjectName("Cunit")
        self.Clientok = QtWidgets.QPushButton(Clientinit)
        self.Clientok.setGeometry(QtCore.QRect(320, 150, 75, 23))
        self.Clientok.setObjectName("Clientok")

        self.retranslateUi(Clientinit)
        QtCore.QMetaObject.connectSlotsByName(Clientinit)

    def retranslateUi(self, Clientinit):
        _translate = QtCore.QCoreApplication.translate
        Clientinit.setWindowTitle(_translate("Clientinit", "服务器设置"))
        self.label.setText(_translate("Clientinit", "服务器IP地址："))
        self.label_2.setText(_translate("Clientinit", "端口号："))
        self.label_3.setText(_translate("Clientinit", "数据库单元："))
        self.Clientport.setText(_translate("Clientinit", "48010"))
        self.Clientok.setText(_translate("Clientinit", "确定"))
