# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'IOlistDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_IOlistinit(object):
    def setupUi(self, IOlistinit):
        IOlistinit.setObjectName("IOlistinit")
        IOlistinit.resize(400, 218)
        self.IOlistok = QtWidgets.QDialogButtonBox(IOlistinit)
        self.IOlistok.setGeometry(QtCore.QRect(30, 150, 341, 32))
        self.IOlistok.setOrientation(QtCore.Qt.Horizontal)
        self.IOlistok.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.IOlistok.setObjectName("IOlistok")
        self.label = QtWidgets.QLabel(IOlistinit)
        self.label.setGeometry(QtCore.QRect(30, 50, 54, 12))
        self.label.setObjectName("label")
        self.fileph = QtWidgets.QTextEdit(IOlistinit)
        self.fileph.setGeometry(QtCore.QRect(90,48,210,24))
        self.filesel = QtWidgets.QPushButton(IOlistinit)
        self.filesel.setGeometry(QtCore.QRect(305,50,20,20))

        self.retranslateUi(IOlistinit)
        self.IOlistok.rejected.connect(IOlistinit.reject)
        QtCore.QMetaObject.connectSlotsByName(IOlistinit)

    def retranslateUi(self, IOlistinit):
        _translate = QtCore.QCoreApplication.translate
        IOlistinit.setWindowTitle(_translate("IOlistinit", "点表设置"))
        self.label.setText(_translate("IOlistinit", "点表路径："))
        self.filesel.setText("..")