# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ClientDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from UA_Logic.Values import uaclient

class Ui_Clientinit(object):
    def setupUi(self, Clientinit):
        Clientinit.setObjectName("Clientinit")
        Clientinit.resize(473, 201)
        self.Clientok = QtWidgets.QDialogButtonBox(Clientinit)
        self.Clientok.setGeometry(QtCore.QRect(110, 150, 341, 32))
        self.Clientok.setOrientation(QtCore.Qt.Horizontal)
        self.Clientok.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.Clientok.setObjectName("Clientok")
        self.label = QtWidgets.QLabel(Clientinit)
        self.label.setGeometry(QtCore.QRect(20, 40, 81, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Clientinit)
        self.label_2.setGeometry(QtCore.QRect(40, 80, 54, 12))
        self.label_2.setObjectName("label_2")
        self.ClientIP = QtWidgets.QTextEdit(Clientinit)
        self.ClientIP.setGeometry(QtCore.QRect(100, 40, 191, 21))
        self.ClientIP.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.ClientIP.setObjectName("ClientIP")
        self.Clientport = QtWidgets.QTextEdit(Clientinit)
        self.Clientport.setGeometry(QtCore.QRect(100, 80, 111, 21))
        self.Clientport.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.Clientport.setObjectName("Clientport")
        self.label_3 = QtWidgets.QLabel(Clientinit)
        self.label_3.setGeometry(QtCore.QRect(20, 120, 71, 16))
        self.label_3.setObjectName("label_3")
        self.Cunit = QtWidgets.QTextEdit(Clientinit)
        self.Cunit.setGeometry(QtCore.QRect(100, 120, 111, 21))
        self.Cunit.setObjectName("Cunit")

        self.retranslateUi(Clientinit)

        self.Clientok.rejected.connect(Clientinit.reject)
        QtCore.QMetaObject.connectSlotsByName(Clientinit)

    def retranslateUi(self, Clientinit):
        _translate = QtCore.QCoreApplication.translate
        Clientinit.setWindowTitle(_translate("Clientinit", "服务器设置"))
        self.label.setText(_translate("Clientinit", "服务器IP地址："))
        self.label_2.setText(_translate("Clientinit", "端口号："))
        self.Clientport.setHtml(_translate("Clientinit", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">48010</p></body></html>"))
        self.label_3.setText(_translate("Clientinit", "数据库单元："))
        self.Cunit.setText(uaclient['unit'])
        self.ClientIP.setText(uaclient['ip'])